
name: dbt_demo
version: "1.0.0"
config-version: 2

profile: dbt_demo

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages", "logs"]

models:
  dbt_demo:
    staging:
      +materialized: view
    intermediate:
      +materialized: ephemeral
    marts:
      +materialized: table
